---
- name: install firewalld
  yum:
    name: firewalld
    state: latest

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: config firewalld
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    service: "{{ firewall_service }}"

