---
# tasks file for myapache

- name: install httpd, firewalld
  yum:
    name: "{{ item }}"
    state: installed
  with_items: 
    - httpd
    - firewalld

- name: copy conf file
  template:
    src: apache_httpdconf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0444
  when: apache_enabled

- name: copy index file
  template:
    src: apache_indexhtml.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0444
  when: apache_enabled

- name: start httpd, firewalld
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - httpd
    - firewalld
  when: apache_enabled

- name: oper port
  firewalld:
    state: enabled
    port: 80/tcp
    immediate: true
    permanent: true
  when: apache_enabled

