---
- name: jinja2 yaml
  hosts: all
  user: devops
  become: true
  vars:
    system_owner: milanj

  tasks:
    - name: apply template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
