---
- name: setup httpd and firewalld
  hosts: servera.lab.example.com
  become: yes
  tasks:
    - name: yum httpd&firewalld
      yum:
        name: 
          - httpd
          - firewalld
        state: latest
      become: yes
    - name: httpd started
      service:
        name: httpd
        enabled: true
        state: started
      remote_user: devops
      become: yes
    - name: firewalld started
      service:
        name: firewalld 
        enabled: true
        state: started
    - name: permit httpd
      firewalld:
        state: enabled
        service: http
        permanent: true
        immediate: yes
    - name: enable httpd
      service:
        name: httpd
        enabled: true
        state: started

    - name: fillin index.html
      copy:
        dest: /var/www/html/index.html
        content: "Welcome to the example.com internet!\n" 

- name: validate httpd
  hosts: localhost
  become: no
  tasks:
    - name: connect to httpd
      uri:
        url: http://servera.lab.example.com
        status_code: 200
