---
- name: Install Apache and start the service
  hosts: webserver
  tasks:
    - name: Install required packages
      yum:
        name: "{{ ansible_local.custom.general.service }}"
        state: latest
    - name: Start the service
      service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"

