---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
  - name: check local time
    command: date
    register: command_result
    changed_when: false

  - name: print local time
    debug:
      var: command_result['stdout']

  - block:
    - name: Install http package
      yum:
        name: httpd
        state: latest
      failed_when: true

    rescue:
      - name: Install mariacb package
        yum:
          name: mariadb-server
          state: latest

    always:
      - name: Start mariadb
        service:
          name: mariadb
          state: started
